export const claimTypes = [
    {key:'1', value:'Personal', disabled: true},
    {key:'2', value:'Home'},
    {key:'3', value:'Auto'},
    {key:'4', value:'Short Term Disability'},
    {key:'5', value:'Long Term Disability'},
    {key:'6', value:'Business', disabled: true},
    {key:'7', value:'Property'},
    {key:'8', value:'Liability'},
    {key:'9', value:'Workers Compensation'},
  ]

export const companies = [
    {
        name: 'Aetna ',
        claimsSupported: ['Short Term Disability', 'Long Term Disability'],
        shortTermDisabilityData: [{ popUp: false, data: '' }],
        longTermDisabilityData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: true,
            data: {
                message: 'Aetna does not have a payment portal. Please call 1-800-872-3862 to make a payment.',
                phone: '18008723862',
                link: 'https://www.aetna.com/individuals-families/bill-pay.html'
            }
        }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://nam.edu/wp-content/uploads/2019/06/Aetna-Logo-PNG-Transparent-2.png',
        key: this.name,
    },
    {
        name: 'AmTrust',
        claimsSupported: ['Workers Compensation'],
        workersCompensationData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://mlxwx3bywoz1.i.optimole.com/cb:4l67~34919/w:600/h:601/q:auto/ig:avif/f:best/https://www.globalcoverage.com/wp-content/uploads/sites/1255/2017/11/AmTrustInsurance.png',
        key: this.name,
    },
    {
        name: 'Anthem',
        claimsSupported: ['Short Term Disability', 'Long Term Disability'],
        shortTermDisabilityData: [{ popUp: false, data: '' }],
        longTermDisabilityData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Anthem_Inc_logo.png',
        key: this.name,
    },
    {
        name: 'Companion Life',
        claimsSupported: ['Short Term Disability', 'Long Term Disability'],
        shortTermDisabilityData: [{ popUp: false, data: '' }],
        longTermDisabilityData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://assets-global.website-files.com/5cd06573f0a28dce76ef883f/5d07f805eebf47099f8a4108_logo-companion.png',
        key: this.name,
    },
    {
        name: 'Donegal',
        claimsSupported: ['Home', 'Auto'],
        homeData: [{ popUp: false, data: '' }],
        autoData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://www.onespan.com/sites/default/files/2020-03/donegal%20logo.png',
        key: this.name,
    },
    {
        name: 'EMC',
        claimsSupported: ['Workers Compensation'],
        workersCompensationData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://pnptc-media.s3.amazonaws.com/images/EMC_Logo_gradient.max-500x500.png',
        key: this.name,
    },
    {
        name: 'Encompass',
        claimsSupported: ['Home', 'Auto'],
        homeData: [{ popUp: false, data: '' }],
        autoData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://ameristaragency.com/wp-content/uploads/2019/06/download-2.png',
        key: this.name,
    },
    {
        name: 'Grange',
        claimsSupported: ['Workers Compensation'],
        workersCompensationData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Grange_Insurance_logo.svg/1200px-Grange_Insurance_logo.svg.png',
        key: this.name,
    },
    {
        name: 'Guardian Life',
        claimsSupported: ['Short Term Disability', 'Long Term Disability'],
        shortTermDisabilityData: [{ popUp: false, data: '' }],
        longTermDisabilityData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Guardian_Insurance_logo.svg/1024px-Guardian_Insurance_logo.svg.png',
        key: this.name,
    },
    {
        key: '11',
        name: 'New York Life',
        claimsSupported: ['Short Term Disability', 'Long Term Disability'],
        shortTermDisabilityData: [{ popUp: false, data: '' }],
        longTermDisabilityData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://logo-logos.com/2016/12/New_York_Life_Insurance_logo.png',
        key: this.name,
    },
    {
        name: 'Pie Insurance',
        claimsSupported: ['Workers Compensation'],
        workersCompensationData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://pieinsurance.com/images/pie-logo.png',
        key: this.name,
    },
    {
        name: 'Progressive',
        claimsSupported: ['Auto'],
        autoData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://1000logos.net/wp-content/uploads/2023/01/Progressive-logo.png',
        key: this.name,
    },
    {
        name: 'Sun Life',
        claimsSupported: ['Short Term Disability', 'Long Term Disability'],
        shortTermDisabilityData: [{ popUp: false, data: '' }],
        longTermDisabilityData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://www.sunlife.ca/content/dam/sunlife/regional/canada/images/grs/Sun_Life_Logo.png',
        key: this.name,
    },
    {
        name: 'Travelers',
        claimsSupported: ['Home', 'Auto'],
        homeData: [{ popUp: false, data: '' }],
        autoData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://1000logos.net/wp-content/uploads/2023/01/Travelers-logo.png',
        key: this.name,
    },
    {
        name: 'Universal',
        claimsSupported: ['Home'],
        homeData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://tayloragency.com/content/uploads/2017/12/Universal-North-America-Logo.png',
        key: this.name,
    },
    {
        name: 'Unum',
        claimsSupported: ['Short Term Disability', 'Long Term Disability'],
        shortTermDisabilityData: [{ popUp: false, data: '' }],
        longTermDisabilityData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Unum_Group_logo.svg/1200px-Unum_Group_logo.svg.png',
        key: this.name,
    },
    {
        name: 'Utica',
        claimsSupported: ['Workers Compensation'],
        workersCompensationData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://secure.uticanational.com/marketing/annual-report/assets/img/unig-logo-two-lines.png',
        key: this.name,
    },
    {
        name: 'Alliant Health Plans',
        claimsSupported: [],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://alliantplans.com/wp-content/uploads/2021/11/Alliant-Health-Plans-Logo-Blue.png',
        key: this.name,
    },
    {
        name: 'Cigna',
        claimsSupported: ['Workers Compensation'],
        workersCompensationData: [{ popUp: false, data: '' }],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://1000logos.net/wp-content/uploads/2020/07/Cigna-Logo.png',
        key: this.name,
    },
    {
        name: 'Allstate',
        claimsSupported: [],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://1000logos.net/wp-content/uploads/2021/12/Allstate-Logo-1999.png',
        key: this.name,
    },
    {
        name: 'Angle',
        claimsSupported: [],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://bookface-images.s3.amazonaws.com/logos/129af1f6a91bea2be9ec0035adf5cd65f5aa2bc0.png',
        key: this.name,
    },
    {
        name: 'Trustmark',
        claimsSupported: [],
        paymentData: [{ popUp: false, data: '' }],
        idCardData: [{ popUp: false, data: '' }],
        loginData: [{ popUp: false, data: '' }],
        logo: 'https://www.getltci.com/hs-fs/hubfs/belch.io/template-assets/Trustmark-logo-400x164.png?width=400&height=164&name=Trustmark-logo-400x164.png',
        key: this.name,
    },
];

export const documents = [
    {
        docName: 'Auto ID Card.pdf',
    },
    {
        docName: 'Auto Policy.pdf',
    },
    {
        docName: 'Home Policy.pdf',
    },
]

export const employees = [
    {
        name: 'David Pennington III',
        title: 'Managing Director',
        phone: '',
        email: '',
    },
    {
        name: 'Brian Peters',
        title: 'Managing Director',
        phone: '',
        email: '',
    },
    {
        name: 'David Pennington IV',
        title: 'Agent',
        phone: '',
        email: '',
    }
]

export default {
    claimTypes,
    companies,
    documents,
    employees,
}